### ISSUE TITLE
Possible to support required properties?

### ISSUE THREAD

**Issue by twe4ked** [kurtbuilds/oasgen#1]
Hey thanks for creating this. Is it possible to support required properties?

I'm using the schema to generate TypesScript types (https://github.com/fabien0102/openapi-codegen) and it's much nicer if the fields are marked as required.

**Comment by kurtbuilds** [comment]
Thanks for this. It's a bug, but technically a breaking change, so it's released as 0.8.0.

Let me know if you encounter issues with it.

**Comment by twe4ked** [comment]
Works great, thanks for the quick response!
