### ISSUE TITLE
Add support for actix's web::Query

### ISSUE THREAD

**Issue by s-fabian** [kurtbuilds/oasgen#11]
When using `#[oasgen]` on an actix route with the `web::Query` extractor, the `Server::get` function panics with the following message: `Call parameters() for Query, not schema().`

See [here](https://github.com/s-fabian/oasgen-issue/blob/main/src/main.rs) for an example.

**Comment by kurtbuilds** [comment]
Sorry about that. Had a decent sized refactor a few days ago and some things slipped through.

Published fix as 0.18.4. I'll add your example as a regression test too. Thank you for including that.
